adjective1 = input("Give me an adjective: ")
verb1 = input("Give me a verb: ")
verb2 = input("Give me a verb: ")
name1 = input("Give me a name: ")
time = input("Give me a time: ")
body_part = input("Give me a body part: ")
interjection = input("Give me an interjection: ")
superlative = input("Give me a superlative: ")
place = input("Give me a place: ")
adverb = input("Give me an adverb: ")
noun = input("Give me a noun: ")
food = input("Give me a food: ")
plural_animal = input("Give me a plural animal: ")
salutation = input("Give me a salutation: ")
adjective3 = input("Give me an adjective: ")
noun2 = input("Give me a noun: ")
number = input("Give me a number: ")
verb3 = input("Give me a verb: ")

print('It was a/an ' + adjective1 + ' summer afternoon when he ' + verb1 + ' by me and said, "Hey." My eyes ' + verb2 + ' as my heartbeat fluttered. In that instant I knew ' + name1 + ' and I would love each other for ' + time + '.')
print('"Hey," I said back. Then he looked deep into my ' + body_part + ' and replied, "' + interjection + ', you are the ' + superlative + ' girl I have ever seen."')
print('We sat in the ' + place + ' and stared at each other for hours. As his hand ' + adverb + ' touched my hand, sparks flew.')
print('We talked about ' + noun + ' and other important details of our lives. He loved ' + food + ' and ' + plural_animal + ' almost as much as I loved him. He offered to show me his ' + noun2 + ' collection. For ' + number + ' days we talked and ' + verb3 + '. The warm summer days turned ' + adjective3 + ' and he had to leave. I didn\'t even get to say ' + salutation + '.')
